### ISSUE TITLE
All Complete!

### ISSUE THREAD

**Issue by JackMcIlraith** [michaelchiumya/unittest#6]
Hi Michael,

I've updated the test code and corrected the expected dead status for the alien!
I also just added the missing check and {} from the 2 rRaygun functions that were causing them to fail the test! Nice code btw, easy to understand!
I merged your dev branch back to main and closed the pull request.

You can mark this issue closed and that's the work done!

**Comment by michaelchiumya** [comment]
sound job Jack, and thanks
